import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Background from "../components/Background";
import Nav from "../components/Nav";
import Banner from '../components/Banner';

export default function Home() {
  return (
    <>
      <Head>
        <title>WeTeck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/weteck.png" />
      </Head>
      <Background />
      <Nav />
      <Banner />
    </>
  )
}
