import Head from 'next/head'
import Background from "../components/Background";
import Nav from "../components/Nav";
import _Footer from '../components/Footer';
import Content1 from '../components/Content1';
import About2 from '../components/About2';
import Services3 from '../components/Services3';
import Portfolio4 from '../components/Portfolio4';
import Stats5 from '../components/Stats5';

export default function Home() {
  return (
    <>
      <Head>
        <title>WeTeck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/weteck.png" />
      </Head>
      <Background />
      <Nav />
      <Content1 />
      <About2 />
      <Services3 />
      <Portfolio4 />
      <Stats5 />
      <_Footer />
    </>
  )
}
