import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weteck Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <Link href="/"><a><li>Our Services</li></a></Link>
          <Link href="/"><a><li>Portfolio</li></a></Link>
          <Link href="/"><a><li>About Us</li></a></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h3>We Believe in Providing The Best</h3>
        <h1>Customer Service</h1>
        <h3>In Addition To High-Quality Softwares</h3>
        <p>We build a teamwork relationship with our customers to understand their vision and utilize our best expertise to make it a successful reality.</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
